#!/usr/bin/env python3
"""Tests for check_configs.py, run against synthetic build trees.

The acceptance criterion for the config matrix is "CI goes red if any assertion
is deliberately broken". These tests are that spot-check, mechanised: each one
takes a known-good .config, breaks exactly one invariant, and asserts the
matching check fails. They need no SDK and no build, so they run in the lint job.

    python scripts/test_check_configs.py
"""

import os
import shutil
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import check_configs  # noqa: E402  (needs the path above)

# A minimal .config carrying every symbol the checks look at, as a real debug
# XIAO build emits them.
GOOD_XIAO = """\
# Generated by Kconfig, do not edit
CONFIG_BOARD="xiao_ble"
CONFIG_FLASH_LOAD_OFFSET=0x27000
CONFIG_UART_1_ASYNC=y
# CONFIG_UART_1_INTERRUPT_DRIVEN is not set
CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=1
CONFIG_BT_FILTER_ACCEPT_LIST=y
CONFIG_BT_SMP=y
CONFIG_BT_SETTINGS=y
CONFIG_NVS=y
CONFIG_SERIAL=y
CONFIG_LOG=y
CONFIG_BOARD_SERIAL_BACKEND_CDC_ACM=y
"""

# The production XIAO: same, minus logging and the USB CDC-ACM console.
GOOD_XIAO_PROD = (
    GOOD_XIAO
    .replace("CONFIG_LOG=y\n", "# CONFIG_LOG is not set\n")
    .replace("CONFIG_BOARD_SERIAL_BACKEND_CDC_ACM=y\n",
             "# CONFIG_BOARD_SERIAL_BACKEND_CDC_ACM is not set\n")
)


def failed_ids(results):
    return sorted({check_id for check_id, _desc, ok, _detail in results if not ok})


class CheckConfigsTest(unittest.TestCase):
    def setUp(self):
        self.root = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.root, True)

    def build_dir(self, config_text, name="build_xiao"):
        """Write a synthetic build dir containing just the app's .config."""
        path = os.path.join(self.root, name)
        config = os.path.join(path, check_configs.CONFIG_PATH)
        os.makedirs(os.path.dirname(config), exist_ok=True)
        with open(config, "w", encoding="utf-8") as f:
            f.write(config_text)
        return path

    def run_checks(self, config_text, target="xiao", **kwargs):
        path = self.build_dir(config_text, **kwargs)
        return check_configs.check_target(
            target, check_configs.TARGETS[target], path), path

    # --- the happy path ---------------------------------------------------

    def test_good_debug_build_passes(self):
        results, _ = self.run_checks(GOOD_XIAO)
        self.assertEqual(failed_ids(results), [])

    def test_good_prod_build_passes(self):
        results, _ = self.run_checks(GOOD_XIAO_PROD, target="xiao_prod",
                                     name="build_xiao_prod")
        self.assertEqual(failed_ids(results), [])

    # --- A7: flash offset -------------------------------------------------

    def test_wrong_offset_fails(self):
        """The Pro Micro boot-loop bug: linked at 0x0, copied to 0x26000."""
        broken = GOOD_XIAO.replace("CONFIG_FLASH_LOAD_OFFSET=0x27000",
                                   "CONFIG_FLASH_LOAD_OFFSET=0x0")
        results, _ = self.run_checks(broken)
        self.assertIn("A7", failed_ids(results))

    def test_missing_offset_reads_as_zero(self):
        broken = GOOD_XIAO.replace("CONFIG_FLASH_LOAD_OFFSET=0x27000\n", "")
        results, _ = self.run_checks(broken)
        self.assertIn("A7", failed_ids(results))

    def test_dk_offset_zero_passes_when_unset(self):
        """The DK has no bootloader: 0x0 is correct, and Kconfig omits it."""
        text = GOOD_XIAO.replace("CONFIG_FLASH_LOAD_OFFSET=0x27000\n", "")
        results, _ = self.run_checks(text, target="dk", name="build_devkit")
        self.assertNotIn("A7", failed_ids(results))

    def test_offset_accepts_decimal_notation(self):
        text = GOOD_XIAO.replace("CONFIG_FLASH_LOAD_OFFSET=0x27000",
                                 "CONFIG_FLASH_LOAD_OFFSET=159744")
        results, _ = self.run_checks(text)
        self.assertNotIn("A7", failed_ids(results))

    # --- A8: the async-UART gating ---------------------------------------

    def test_async_uart_disabled_fails(self):
        broken = GOOD_XIAO.replace("CONFIG_UART_1_ASYNC=y\n", "")
        results, _ = self.run_checks(broken)
        self.assertIn("A8", failed_ids(results))

    def test_interrupt_driven_uart1_fails(self):
        """What the USB CDC-ACM console silently turns back on -> -ENOSYS."""
        broken = GOOD_XIAO.replace(
            "# CONFIG_UART_1_INTERRUPT_DRIVEN is not set",
            "CONFIG_UART_1_INTERRUPT_DRIVEN=y")
        results, _ = self.run_checks(broken)
        self.assertIn("A8", failed_ids(results))

    # --- A9: what prod.conf may strip ------------------------------------

    def test_prod_keeping_logging_fails(self):
        results, _ = self.run_checks(GOOD_XIAO, target="xiao_prod",
                                     name="build_xiao_prod")
        self.assertIn("A9", failed_ids(results))

    def test_prod_stripping_the_pairing_lock_fails(self):
        """The invariant: production needs the bond lock most of all."""
        for symbol in ("CONFIG_BT_SMP=y", "CONFIG_BT_SETTINGS=y",
                       "CONFIG_NVS=y"):
            broken = GOOD_XIAO_PROD.replace(symbol + "\n", "")
            results, _ = self.run_checks(broken, target="xiao_prod",
                                         name="build_xiao_prod")
            self.assertIn("A9", failed_ids(results), symbol)

    def test_prod_stripping_serial_fails(self):
        broken = GOOD_XIAO_PROD.replace("CONFIG_SERIAL=y\n", "")
        results, _ = self.run_checks(broken, target="xiao_prod",
                                     name="build_xiao_prod")
        self.assertIn("A9", failed_ids(results))

    def test_debug_build_losing_logging_fails(self):
        """prod.conf leaking into a debug build is a config regression too."""
        results, _ = self.run_checks(GOOD_XIAO_PROD)
        self.assertIn("A9", failed_ids(results))

    # --- A10: Partition Manager stays off ---------------------------------

    def test_partitions_yml_fails(self):
        results, path = self.run_checks(GOOD_XIAO)
        self.assertNotIn("A10", failed_ids(results))

        with open(os.path.join(path, "partitions.yml"), "w") as f:
            f.write("app:\n  address: 0x0\n")
        results = check_configs.check_target(
            "xiao", check_configs.TARGETS["xiao"], path)
        self.assertIn("A10", failed_ids(results))

    def test_nested_partitions_yml_fails(self):
        _results, path = self.run_checks(GOOD_XIAO)
        nested = os.path.join(path, "nrfProxy", "zephyr")
        with open(os.path.join(nested, "partitions.yml"), "w") as f:
            f.write("app:\n  address: 0x0\n")
        results = check_configs.check_target(
            "xiao", check_configs.TARGETS["xiao"], path)
        self.assertIn("A10", failed_ids(results))

    # --- A11: the pairing lock's Kconfig ---------------------------------

    def test_second_connection_or_bond_allowed_fails(self):
        for symbol, broken_value in (("CONFIG_BT_MAX_CONN=1", "CONFIG_BT_MAX_CONN=2"),
                                     ("CONFIG_BT_MAX_PAIRED=1", "CONFIG_BT_MAX_PAIRED=2")):
            broken = GOOD_XIAO.replace(symbol, broken_value)
            results, _ = self.run_checks(broken)
            self.assertIn("A11", failed_ids(results), symbol)

    def test_accept_list_disabled_fails(self):
        broken = GOOD_XIAO.replace("CONFIG_BT_FILTER_ACCEPT_LIST=y\n", "")
        results, _ = self.run_checks(broken)
        self.assertIn("A11", failed_ids(results))

    # --- plumbing ---------------------------------------------------------

    def test_missing_build_dir_reports_cleanly(self):
        with self.assertRaises(check_configs.CheckError):
            check_configs.check_target(
                "xiao", check_configs.TARGETS["xiao"],
                os.path.join(self.root, "never_built"))

    def test_empty_config_reports_cleanly(self):
        path = self.build_dir("# nothing here\n")
        with self.assertRaises(check_configs.CheckError):
            check_configs.check_target(
                "xiao", check_configs.TARGETS["xiao"], path)

    def test_main_exit_codes(self):
        self.build_dir(GOOD_XIAO)
        self.assertEqual(
            check_configs.main(["xiao", "--proj", self.root]), 0)

        self.build_dir(GOOD_XIAO.replace("CONFIG_UART_1_ASYNC=y\n", ""))
        self.assertEqual(
            check_configs.main(["xiao", "--proj", self.root]), 1)

    def test_build_dir_override_requires_one_target(self):
        with self.assertRaises(SystemExit):
            check_configs.main(["dk", "xiao", "--build-dir", self.root])

    def test_target_table_matches_the_build_wrappers(self):
        """The wrappers are the source of truth for board + build dir."""
        repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        with open(os.path.join(repo, "build.sh"), encoding="utf-8") as f:
            build_sh = f.read()
        for name, spec in check_configs.TARGETS.items():
            self.assertIn("[{}]=\"{}|{}|".format(name, spec["board"],
                                                 spec["build_dir"]),
                          build_sh)


if __name__ == "__main__":
    unittest.main()
